# Generated by Django 4.1.4 on 2022-12-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_category_createdat_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="coverImg",
            field=models.ImageField(upload_to="static/media/article-imgs/"),
        ),
    ]
